name: Testing

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go: [1.18.x, 1.19.x, 1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: build
    runs-on: ubuntu-latest #目前只支持ubuntu，因为镜像问题
    services:
      etcd:
        image: gcr.io/etcd-development/etcd:v3.5.0
        ports:
          - 2379:2379
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test -v ./...
